use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use obs_sdk_vault::{CasePolicy, PathCanonicalizationError, VaultScanError, VaultScanService};
use thiserror::Error;

/// Logical transfer direction for import/export operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransferJobKind {
    /// Import files from an external source into a vault destination.
    Import,
    /// Export files from a vault source into an external destination.
    Export,
}

/// Transfer mode for execution boundaries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransferMode {
    /// Compute outcomes without writing destination files.
    DryRun,
    /// Perform filesystem copy operations.
    Apply,
}

/// Classified item kind for transfer planning.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransferItemKind {
    /// Markdown note content (`.md`).
    Markdown,
    /// Obsidian Bases file (`.base`).
    Base,
    /// Any non-markdown/non-base file.
    Asset,
}

/// One planned file transfer item.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TransferItem {
    /// Canonical source-relative normalized path.
    pub normalized_path: String,
    /// Item content classification.
    pub kind: TransferItemKind,
    /// Source file size in bytes.
    pub size_bytes: u64,
}

/// Deterministic import/export transfer plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TransferPlan {
    /// Transfer direction.
    pub job_kind: TransferJobKind,
    /// Canonical source root.
    pub source_root: PathBuf,
    /// Canonical destination root.
    pub destination_root: PathBuf,
    /// Ordered transfer items.
    pub items: Vec<TransferItem>,
    /// Plan generation timestamp as unix epoch milliseconds.
    pub generated_unix_ms: u128,
}

/// Aggregate transfer plan counters.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TransferSummary {
    /// Number of markdown files in plan.
    pub markdown_files: u64,
    /// Number of base files in plan.
    pub base_files: u64,
    /// Number of asset files in plan.
    pub asset_files: u64,
    /// Sum of all planned bytes.
    pub total_bytes: u64,
}

impl TransferPlan {
    /// Compute aggregate counters from current plan items.
    #[must_use]
    pub fn summary(&self) -> TransferSummary {
        let mut markdown_files = 0_u64;
        let mut base_files = 0_u64;
        let mut asset_files = 0_u64;
        let mut total_bytes = 0_u64;

        for item in &self.items {
            match item.kind {
                TransferItemKind::Markdown => markdown_files += 1,
                TransferItemKind::Base => base_files += 1,
                TransferItemKind::Asset => asset_files += 1,
            }
            total_bytes = total_bytes.saturating_add(item.size_bytes);
        }

        TransferSummary {
            markdown_files,
            base_files,
            asset_files,
            total_bytes,
        }
    }
}

/// Execution request for a transfer plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TransferExecutionRequest {
    /// Plan generated by this service boundary.
    pub plan: TransferPlan,
    /// Execution mode.
    pub mode: TransferMode,
    /// When false, existing destination files are skipped.
    pub overwrite_existing: bool,
}

/// One transfer execution failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TransferFailure {
    /// Normalized path that failed.
    pub normalized_path: String,
    /// Error text describing the failure.
    pub error: String,
}

/// Outcome of executing a transfer plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TransferExecutionResult {
    /// Number of files copied to destination.
    pub copied_files: u64,
    /// Number of files intentionally skipped.
    pub skipped_files: u64,
    /// Number of failures encountered.
    pub failed_files: u64,
    /// Collected transfer failures.
    pub failures: Vec<TransferFailure>,
}

/// Import/export service boundary for planning and execution.
pub trait ImportExportServiceBoundary {
    /// Build an import plan from source and destination roots.
    fn plan_import(
        &self,
        source_root: &Path,
        destination_root: &Path,
    ) -> Result<TransferPlan, ImportExportBoundaryError>;

    /// Build an export plan from source and destination roots.
    fn plan_export(
        &self,
        source_root: &Path,
        destination_root: &Path,
    ) -> Result<TransferPlan, ImportExportBoundaryError>;

    /// Execute one transfer plan.
    fn execute_transfer(
        &self,
        request: &TransferExecutionRequest,
    ) -> Result<TransferExecutionResult, ImportExportBoundaryError>;
}

/// Filesystem-backed import/export boundary implementation.
#[derive(Debug, Clone, Copy)]
pub struct FilesystemImportExportService {
    case_policy: CasePolicy,
}

impl FilesystemImportExportService {
    /// Create a filesystem boundary with explicit path case policy.
    #[must_use]
    pub fn new(case_policy: CasePolicy) -> Self {
        Self { case_policy }
    }
}

impl Default for FilesystemImportExportService {
    fn default() -> Self {
        Self {
            case_policy: CasePolicy::Sensitive,
        }
    }
}

impl ImportExportServiceBoundary for FilesystemImportExportService {
    fn plan_import(
        &self,
        source_root: &Path,
        destination_root: &Path,
    ) -> Result<TransferPlan, ImportExportBoundaryError> {
        self.plan_transfer(TransferJobKind::Import, source_root, destination_root)
    }

    fn plan_export(
        &self,
        source_root: &Path,
        destination_root: &Path,
    ) -> Result<TransferPlan, ImportExportBoundaryError> {
        self.plan_transfer(TransferJobKind::Export, source_root, destination_root)
    }

    fn execute_transfer(
        &self,
        request: &TransferExecutionRequest,
    ) -> Result<TransferExecutionResult, ImportExportBoundaryError> {
        if request.mode == TransferMode::DryRun {
            return Ok(TransferExecutionResult {
                copied_files: 0,
                skipped_files: request.plan.items.len() as u64,
                failed_files: 0,
                failures: Vec::new(),
            });
        }

        let mut copied_files = 0_u64;
        let mut skipped_files = 0_u64;
        let mut failures = Vec::new();

        for item in &request.plan.items {
            let source_path = request.plan.source_root.join(&item.normalized_path);
            let destination_path = request.plan.destination_root.join(&item.normalized_path);

            if destination_path.exists() && !request.overwrite_existing {
                skipped_files += 1;
                continue;
            }

            if let Some(parent) = destination_path.parent() {
                fs::create_dir_all(parent).map_err(|source| {
                    ImportExportBoundaryError::CreateDestinationDirectory {
                        path: parent.to_path_buf(),
                        source,
                    }
                })?;
            }

            match fs::copy(&source_path, &destination_path) {
                Ok(_) => copied_files += 1,
                Err(source) => {
                    failures.push(TransferFailure {
                        normalized_path: item.normalized_path.clone(),
                        error: source.to_string(),
                    });
                }
            }
        }

        Ok(TransferExecutionResult {
            copied_files,
            skipped_files,
            failed_files: failures.len() as u64,
            failures,
        })
    }
}

impl FilesystemImportExportService {
    fn plan_transfer(
        &self,
        job_kind: TransferJobKind,
        source_root: &Path,
        destination_root: &Path,
    ) -> Result<TransferPlan, ImportExportBoundaryError> {
        let scanner = VaultScanService::from_root(source_root, self.case_policy)
            .map_err(|source| ImportExportBoundaryError::CreateScanner { source })?;
        let manifest = scanner
            .scan()
            .map_err(|source| ImportExportBoundaryError::ScanSource { source })?;

        let destination_root = canonicalize_directory(destination_root)?;
        let mut items = Vec::with_capacity(manifest.entries.len());
        for entry in manifest.entries {
            items.push(TransferItem {
                kind: classify_item_kind(&entry.normalized),
                normalized_path: entry.normalized,
                size_bytes: fs::metadata(&entry.absolute)
                    .map_err(|source| ImportExportBoundaryError::ReadMetadata {
                        path: entry.absolute.clone(),
                        source,
                    })?
                    .len(),
            });
        }

        Ok(TransferPlan {
            job_kind,
            source_root: manifest.root,
            destination_root,
            items,
            generated_unix_ms: current_unix_ms()?,
        })
    }
}

fn current_unix_ms() -> Result<u128, ImportExportBoundaryError> {
    Ok(SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|source| ImportExportBoundaryError::Clock { source })?
        .as_millis())
}

fn classify_item_kind(normalized_path: &str) -> TransferItemKind {
    if normalized_path.to_ascii_lowercase().ends_with(".md") {
        TransferItemKind::Markdown
    } else if normalized_path.to_ascii_lowercase().ends_with(".base") {
        TransferItemKind::Base
    } else {
        TransferItemKind::Asset
    }
}

fn canonicalize_directory(path: &Path) -> Result<PathBuf, ImportExportBoundaryError> {
    fs::create_dir_all(path).map_err(|source| {
        ImportExportBoundaryError::CreateDestinationRoot {
            path: path.to_path_buf(),
            source,
        }
    })?;

    fs::canonicalize(path).map_err(
        |source| ImportExportBoundaryError::CanonicalizeDestination {
            path: path.to_path_buf(),
            source,
        },
    )
}

/// Import/export boundary failures.
#[derive(Debug, Error)]
pub enum ImportExportBoundaryError {
    /// Creating scan service failed.
    #[error("failed to initialize import/export scanner: {source}")]
    CreateScanner {
        /// Scanner initialization error.
        #[source]
        source: PathCanonicalizationError,
    },
    /// Scanning source root failed.
    #[error("failed to scan source root for import/export plan: {source}")]
    ScanSource {
        /// Vault scan failure.
        #[source]
        source: VaultScanError,
    },
    /// Reading source file metadata failed.
    #[error("failed to read metadata for source file '{path}': {source}")]
    ReadMetadata {
        /// Source file path.
        path: PathBuf,
        /// Filesystem error.
        #[source]
        source: std::io::Error,
    },
    /// Creating destination root failed.
    #[error("failed to create destination root '{path}': {source}")]
    CreateDestinationRoot {
        /// Destination root path.
        path: PathBuf,
        /// Filesystem error.
        #[source]
        source: std::io::Error,
    },
    /// Canonicalizing destination root failed.
    #[error("failed to canonicalize destination root '{path}': {source}")]
    CanonicalizeDestination {
        /// Destination root path.
        path: PathBuf,
        /// Filesystem error.
        #[source]
        source: std::io::Error,
    },
    /// Creating destination parent directory failed.
    #[error("failed to create destination directory '{path}': {source}")]
    CreateDestinationDirectory {
        /// Destination directory path.
        path: PathBuf,
        /// Filesystem error.
        #[source]
        source: std::io::Error,
    },
    /// System clock error when generating plan metadata.
    #[error("failed to generate transfer plan timestamp: {source}")]
    Clock {
        /// System time error.
        #[source]
        source: std::time::SystemTimeError,
    },
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::{
        FilesystemImportExportService, ImportExportServiceBoundary, TransferExecutionRequest,
        TransferItemKind, TransferMode,
    };

    #[test]
    fn plan_import_classifies_markdown_base_and_assets() {
        let source = tempdir().expect("source tempdir");
        let destination = tempdir().expect("destination tempdir");

        fs::create_dir_all(source.path().join("notes")).expect("create notes dir");
        fs::create_dir_all(source.path().join("assets")).expect("create assets dir");
        fs::create_dir_all(source.path().join("views")).expect("create views dir");
        fs::write(source.path().join("notes/daily.md"), "# Daily").expect("write markdown");
        fs::write(source.path().join("views/task.base"), "views: []").expect("write base file");
        fs::write(source.path().join("assets/icon.png"), "png").expect("write asset");

        let service = FilesystemImportExportService::default();
        let plan = service
            .plan_import(source.path(), destination.path())
            .expect("plan import");

        assert_eq!(plan.items.len(), 3);
        let kinds: Vec<TransferItemKind> = plan.items.iter().map(|item| item.kind).collect();
        assert!(kinds.contains(&TransferItemKind::Markdown));
        assert!(kinds.contains(&TransferItemKind::Base));
        assert!(kinds.contains(&TransferItemKind::Asset));

        let summary = plan.summary();
        assert_eq!(summary.markdown_files, 1);
        assert_eq!(summary.base_files, 1);
        assert_eq!(summary.asset_files, 1);
    }

    #[test]
    fn execute_transfer_dry_run_reports_skipped_without_writes() {
        let source = tempdir().expect("source tempdir");
        let destination = tempdir().expect("destination tempdir");

        fs::write(source.path().join("note.md"), "# Note").expect("write source note");

        let service = FilesystemImportExportService::default();
        let plan = service
            .plan_export(source.path(), destination.path())
            .expect("plan export");

        let result = service
            .execute_transfer(&TransferExecutionRequest {
                plan,
                mode: TransferMode::DryRun,
                overwrite_existing: false,
            })
            .expect("execute dry run");

        assert_eq!(result.copied_files, 0);
        assert_eq!(result.failed_files, 0);
        assert_eq!(result.skipped_files, 1);
        assert!(!destination.path().join("note.md").exists());
    }

    #[test]
    fn execute_transfer_apply_copies_files_and_respects_overwrite() {
        let source = tempdir().expect("source tempdir");
        let destination = tempdir().expect("destination tempdir");

        fs::create_dir_all(source.path().join("notes")).expect("create notes dir");
        fs::write(source.path().join("notes/daily.md"), "# v1").expect("write source note");

        let service = FilesystemImportExportService::default();
        let plan = service
            .plan_export(source.path(), destination.path())
            .expect("plan export");

        let first = service
            .execute_transfer(&TransferExecutionRequest {
                plan: plan.clone(),
                mode: TransferMode::Apply,
                overwrite_existing: false,
            })
            .expect("execute apply first");
        assert_eq!(first.copied_files, 1);
        assert_eq!(first.failed_files, 0);
        assert_eq!(first.skipped_files, 0);
        assert_eq!(
            fs::read_to_string(destination.path().join("notes/daily.md")).expect("read copied"),
            "# v1"
        );

        fs::write(source.path().join("notes/daily.md"), "# v2").expect("update source note");

        let second = service
            .execute_transfer(&TransferExecutionRequest {
                plan: plan.clone(),
                mode: TransferMode::Apply,
                overwrite_existing: false,
            })
            .expect("execute apply second");
        assert_eq!(second.copied_files, 0);
        assert_eq!(second.skipped_files, 1);
        assert_eq!(
            fs::read_to_string(destination.path().join("notes/daily.md")).expect("read copied"),
            "# v1"
        );

        let third = service
            .execute_transfer(&TransferExecutionRequest {
                plan,
                mode: TransferMode::Apply,
                overwrite_existing: true,
            })
            .expect("execute apply overwrite");
        assert_eq!(third.copied_files, 1);
        assert_eq!(third.skipped_files, 0);
        assert_eq!(
            fs::read_to_string(destination.path().join("notes/daily.md")).expect("read copied"),
            "# v2"
        );
    }
}
